export default {
  worker: {
    name: "blog",
    entrypoint: "src/worker.ts",
    compatibilityDate: "2026-03-13",
    workersDev: false,
    previewUrls: false,
    domains: ["xingkaixin.me", "www.xingkaixin.me", "blog.xingkaixin.me"],
    env: { ASSETS: { type: "assets" } },
    assets: {
      htmlHandling: "force-trailing-slash",
      notFoundHandling: "404-page",
      runWorkerFirst: [
        "/*",
        "!/.well-known/api-catalog",
        "!/_astro/*",
        "!/cover/*",
        "!/fonts/*",
        "!/og/*",
        "!/openapi.json",
        "!/posts/images/*",
        "!/projects/*.png",
        "!/projects/*.svg",
        "!/projects/*.webp",
        "!/agent-routes.json",
        "!/avatar.webp",
        "!/f1-car.png",
        "!/feed.xml",
        "!/finish-flag.png",
        "!/logo.svg",
        "!/llms.txt",
        "!/robots.txt",
        "!/search-index.json",
        "!/sitemap.xml",
        "!/webmcp/*",
      ],
    },
  },
};
